"""add_dialog_message

Revision ID: a909570fdf70
Revises: 92a2a5ab86f4
Create Date: 2025-07-01 10:28:24.108345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a909570fdf70'
down_revision: Union[str, Sequence[str], None] = '92a2a5ab86f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('Order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Order', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('Order', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('Product', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('Product', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('Product', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('Product', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('Order', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('Order', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('Order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('messages')
    op.drop_table('dialogs')
    # ### end Alembic commands ###
