"""product_order_quantity_add

Revision ID: bba5153b8ac6
Revises: be3e63d0ae77
Create Date: 2025-07-18 18:23:27.365101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba5153b8ac6'
down_revision: Union[str, Sequence[str], None] = 'be3e63d0ae77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product_Order', sa.Column('product_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Product_Order', 'product_quantity')
    # ### end Alembic commands ###
