"""order_update_1

Revision ID: be3e63d0ae77
Revises: 789bef403a95
Create Date: 2025-07-04 08:56:08.445811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3e63d0ae77'
down_revision: Union[str, Sequence[str], None] = '789bef403a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('Order', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'status')
    op.drop_column('Order', 'delivery_address')
    # ### end Alembic commands ###
