"""product_image_file_id_add

Revision ID: bfb566e3664b
Revises: bba5153b8ac6
Create Date: 2025-07-22 19:30:31.010793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb566e3664b'
down_revision: Union[str, Sequence[str], None] = 'bba5153b8ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('image_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Product', 'image_file_id')
    # ### end Alembic commands ###
